### ISSUE TITLE
nest-extension-module/src/recording_backend_socket.h:32:31: fatal error: recording_backend.h: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by ChenLumen** [nest/nest-extension-module#8] opened 2021-04-19 10:41 UTC
Hi, when I install the nest-extension-module, use the steps in NESTDELOPER SPACE. When I went to the make step, the following error occurred:

nest-extension-module/src/recording_backend_socket.h:32:31: fatal error: recording_backend.h: No such file or directory compilation terminated.

I did not find the file of recording_backend.h. And how should I solve this problem? Thank you very much!

**Comment by jougs** [comment] 2021-04-19 13:40
Which version of NEST are you using?

We are currently refactoring the way NEST extension modules work and this repository is a part of that. It thus only works with current [NEST master](https://github.com/nest/nest-simulator/tree/master). For older versions, please use the example module contained in the source distribution under `examples/MyModule`.

**Comment by ChenLumen** [comment] 2021-04-20 02:05
> Which version of NEST are you using?
> 
> We are currently refactoring the way NEST extension modules work and this repository is a part of that. It thus only works with current [NEST master](https://github.com/nest/nest-simulator/tree/master). For older versions, please use the example module contained in the source distribution under `examples/MyModule`.

My Nest version is 2.18.0, and I have tried 2.20.1, but there is also such a problem. I need to use Nest 3.0?

**Comment by ChenLumen** [comment] 2021-04-20 03:20
Oh sorry, I don't found the _examples/MyModule_ in [this](https://github.com/nest/nest-simulator/tree/master), it's may be delete? So can you give me a detailed address? Thinks!

**Comment by jougs** [comment] 2021-04-20 06:10
Yes.

All 2.x versions of NEST contain a compatible MyModule example in `examples`. This repository only works with NEST master, which will be (hopefully very soon) released as 3.0.

To avoid further confusion, I have added a clarifying note to the [`README`](https://github.com/nest/nest-extension-module/blob/master/README.md) of the repository. Sorry for any inconveniences caused by not doing this earlier.

**Comment by ChenLumen** [comment] 2021-04-21 02:59
> Yes.
> 
> All 2.x versions of NEST contain a compatible MyModule example in `examples`. This repository only works with NEST master, which will be (hopefully very soon) released as 3.0.
> 
> To avoid further confusion, I have added a clarifying note to the [`README`](https://github.com/nest/nest-extension-module/blob/master/README.md) of the repository. Sorry for any inconveniences caused by not doing this earlier.

Thanks, I successed building MyModule in my Ubuntu18.04 machine, but it failed when I run the _pif_psc_alpha help_ command. So, is it because I'm not use the **Linking MyModule into NEST** operation?
When I use **conda create --name nest_2_18_0 -c conda-forge nest-simulator=2.18.0=*** install NEST in my server, there does not appear to be a libltdl.so, libreadline.so, libncures.so, libgsl.so and libgslcblas.so files under the lib folder(it does exist when installed on the local machine). And in my nest-config file, for --libs is indeed configured to the above file.

I'm just a green hand, thank you for your answer!

**Comment by jougs** [comment] 2021-04-21 07:31
I'm afraid that the `help` command might currently not work properly for models that come from an extension module. We're trying to also address this during the refactoring. The problems you're experiencing are most likely not related to not linking the module into NEST. The important part is that you can load the module using the `Install()` command in NEST and that you can instantiate the models coming from it using `Create()`/`Connect()`. Is that the case?

Regarding conda, I am a bit at loss, as I'm not using that myself and we had quite some reports in the past regarding missing libraries. There's just too many moving parts and each case is so different that we can't give general answers. I hope we can also improve the situation with the new version of the extension module system for NEST 3.0. That will still take some time though. Sorry for this.

Finally, may I ask what you actually want to achieve in the end? I.e. what kinds of models do you want to make available via the module you're building? Many model creation tasks are handled much nicer by [NESTML](https://nestml.readthedocs.io/en/latest/) these days and writing a custom extension module should usually be considered the last resort if that does not work. We are very open to discussing extensions to NESTML if you're missing features there.

**Comment by jougs** [comment] 2021-05-31 21:42
I'm closing this as the original issue seems to be resolved. If any new issues come up, feel free to open new issues as you see fits.

**Closed by jougs** 2021-05-31 21:42 UTC
